membersrvc:
   image: membersrvc
   environment:
    - CORE_VM_ENDPOINT=http://172.17.0.1:4243
   command: membersrvc

cli:
  image: hyperledger-peer
  command: ./scripts/infiniteloop.sh
  environment:
    - CORE_VM_ENDPOINT=http://172.17.0.1:4243
    - CORE_PEER_ADDRESSAUTODETECT=true
    - CORE_SECURITY_ENABLED=true

vp0:
  extends:
    file: compose-consensus-4-defaults.yml
    service: vp
  environment:
    - CORE_PEER_ID=vp0
    - CORE_PEER_VALIDATOR_REPLICAS_IPS=vp0:30303 vp1:30303 vp2:30303 vp3:30303
    - CORE_SECURITY_ENROLLID=test_vp0
    - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT


vp1:
  extends:
    service: vp0
  environment:
    - CORE_PEER_ID=vp1
    - CORE_PEER_DISCOVERY_ROOTNODE=vp0:30303
    - CORE_SECURITY_ENROLLID=test_vp1
    - CORE_SECURITY_ENROLLSECRET=5wgHK9qqYaPy


vp2:
  extends:
    service: vp0
  environment:
    - CORE_PEER_ID=vp2
    - CORE_PEER_DISCOVERY_ROOTNODE=vp0:30303
    - CORE_SECURITY_ENROLLID=test_vp2
    - CORE_SECURITY_ENROLLSECRET=vQelbRvja7cJ


vp3:
  extends:
    service: vp0
  environment:
    - CORE_PEER_ID=vp3
    - CORE_PEER_DISCOVERY_ROOTNODE=vp0:30303
    - CORE_SECURITY_ENROLLID=test_vp3
    - CORE_SECURITY_ENROLLSECRET=9LKqKH5peurL
