---
################################################################################
#
#   PBFT PROPERTIES
#
#   - List all algorithm-specific properties here.
#   - Nest keys where appropriate, and sort alphabetically for easier parsing.
#
################################################################################
general:

    # Operational mode: batch, classic, or sieve ( this value is case-insensitive)
    mode: classic

    # Maximum number of validators/replicas we expect in the network
    # Keep the "N" in quotes, or it will be interpreted as "false".
    "N": 4

    # Number of byzantine nodes we will tolerate
    f: 1

    # Checkpoint period is the maximum number of pbft requests that must be
    # re-processed in a view change. A smaller checkpoint period will decrease
    # the amount of time required to recover from an error, but will decrease
    # overall throughput in normal case operation.
    K: 10

   # Affects the log size which is K * logmultiplier
   # For high volume/high latency environments, a higher log size may increase throughput
    logmultiplier: 2

    # How many requests should the primary send per pre-prepare when in "batch" mode
    batchsize: 2

    # Whether the replica should act as a byzantine one; useful for debugging on testnets
    byzantine: false

    # Timeouts
    timeout:

        # Send a pre-prepare if there are pending requests, batchsize isn't reached yet,
        # and this much time has elapsed since the current batch was formed
        batch: 2s

        # How long may a request take between reception and execution
        request: 2s

        # How long may a view change take
        viewchange: 2s
################################################################################
#
#   SECTION: STATETRANSFER
#
#   - This applies to recovery behavior when the replica has detected
#     a state transfer is required
#
#   - This might happen:
#     - During a view change in response to a faulty primary
#     - After a network outage which has isolated the replica
#     - If the current blockchain/state is determined to be corrupt
#
################################################################################
statetransfer:

    # Should a replica attempt to fix damaged blocks?
    # In general, this should be set to true, setting to false will cause
    # the replica to panic, and require a human's intervention to intervene
    # and fix the corruption
    recoverdamage: true

    # The number of blocks to retrieve per sync request
    blocksperrequest: 20

    # Timeouts
    timeout:

        # How long may returning a single block take
        singleblock: 2s

        # How long may returning a single state delta take
        singlestatedelta: 2s

        # How long may transferring the complete state take
        fullstate: 60s
