---
###############################################################################
#
#   NOOPS PROPERTIES
#
# These properties may be passed as environment variables when starting up
# a validating peer with prefix  OPENCHAIN_NOOPS. For example:
#    OPENCHAIN_NOOPS_BLOCK_SIZE=1000
#    OPENCHAIN_NOOPS_BLOCK_TIMEOUT=2
#
###############################################################################

# Define properties for a block: A block is created whenever "size" or "timeout"
# occurs. When we process a block, we grab all transactions in the queue, so
# the number of transactions in a block may be greater than the "size".
block:
    # Number of transactions per block. Must be > 0. Set to 1 for testing
    size: 500

    # Number of seconds to wait for a block. Min is 1 second
    timeout: 1
