---
################################################################################
#
#   PBFT PROPERTIES
#
#   - List all algorithm-specific properties here.
#   - Nest keys where appropriate, and sort alphabetically for easier parsing.
#
################################################################################
general:

    # Algorithm/plugin name goes here. Set it to the package name.
    name: pbft

################################################################################
#
#   SECTION: LEADER
#
#   - This applies to the leader.
#
################################################################################
leader:

    # Set to true if this validating peer is a leader.
    # Useful only for fixed-leader scenarios.
    is: true

    # Send a `PRE_PREPARE` message for every `batch_size` requests received.
    batch_size: 1

    # Or every `tx_period` seconds, whichever one comes first.
    tx_period: 30

################################################################################
#
#   SECTION: REPLICA
#
#   - This applies to all validating peers.
#
################################################################################
replica:

    # The ID of the peer. Should be a non-negative integer.
    # The value set here is only read when running in testing mode.
    id: 0

    timeout:

        # Timeout if you don't receive a PRE_PREPARE message with
        # candidate TXs by the leader within `block` seconds.
        block: 12

        # Timeout if you don't receive a message within `message` seconds.
        message: 3

...
