---
################################################################################
#
#   PBFT PROPERTIES
#
#   - List all algorithm-specific properties here.
#   - Nest keys where appropriate, and sort alphabetically for easier parsing.
#
################################################################################
general:

    # Algorithm/plugin name goes here. Set it to the package name.
    name: pbft

    # How many Byzantine nodes can we tolerate?
    f: 1

    # Checkpoint period.
    K: 128

################################################################################
#
#   SECTION: REPLICA
#
#   - This applies to all validating peers.
#
################################################################################
replica:

    # The ID of the peer. Should be a non-negative integer.
    # The value set here is only read when running in testing mode.
    id: 0

    timeout:

        # Timeout if you don't receive a PRE_PREPARE message with
        # candidate TXs by the leader within `block` seconds.
        block: 12

        # Timeout if you don't receive a message within `message` seconds.
        message: 3

...
